import { deployment } from './deployment';

const releasesUrl = `https://${deployment.rootDomain}/releases`;

export const release = {
  bucket: 'compound-releases-prod',
  downloadUrl: `https://${deployment.rootDomain}/download`,
  releasesUrl,
  // Squirrel.Mac update feed, generated by the landing worker from latest.json.
  feed: 'RELEASES.json',
  feedUrl: `${releasesUrl}/RELEASES.json`,
  dmg: 'Compound-mac-universal.dmg',
  zip: 'Compound-mac-universal.zip',
} as const;

export function releaseVersion(value: unknown): string {
  if (typeof value !== 'string' || !/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(value))
    throw new Error('A release requires a stable x.y.z version');
  return value;
}

/** Squirrel.Mac JSON feed: the app compares `currentRelease` to its own
 * version numerically and downloads `updateTo.url` only when it is newer. */
export function updateFeed(version: string, publishedAt: Date) {
  return {
    currentRelease: version,
    releases: [
      {
        version,
        updateTo: {
          version,
          name: `v${version}`,
          pub_date: publishedAt.toISOString(),
          notes: '',
          url: `${releasesUrl}/v${version}/${release.zip}`,
        },
      },
    ],
  };
}
